spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garden_expert
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate

mqtt:
  broker-url: tcp://localhost:1883
  client-id: webServer
  topics:
    connection: +/connection
    measurement: +/measurement
    status-update: +/statusUpdate
    configuration-update: +/configurationUpdate