
local:
  broker-url: tcp://localhost:1884
  client-id: control_point_1
  topics:
    connection: +/connection
    measurement: +/measurement
    heater: +/heater
    sprinkler: +/sprinkler

remote:
  broker-url: tcp://localhost:1885
  topics:
    connection: +/connection
    status: +/status
    configuration: +/configuration
    measurement: +/measurement


api_url: http://localhost:8080


